use context instead of redux
SkyCell-AG/keycloak-client pull request #1
Opened 2021-03-10 09:59 UTC by AnastasiiaManilnikova

2021-03-10 10:09 UTC, dimaPortyanka commented on src/auth/Auth.js
> +import init from './utils/init'
why utils?

2021-03-10 10:12 UTC, dimaPortyanka commented on src/auth/utils/init.js
> +            getMicrosoftToken(setMicrosoftData)
if we havent received microsoft token we can say this is success
multiple set state is also not good better to use useReducer

2021-03-10 10:14 UTC, dimaPortyanka commented on src/main.js
> +    default as useAuthContext,
all that we want to use in other repos should be exported not to make skycell-ag/keycloack/dist...

2021-03-10 10:14 UTC, dimaPortyanka requested changes
please fix comments

2021-03-10 14:26 UTC, dimaPortyanka commented on src/auth/Auth.js
> +import generateAsyncActions from 'utils/generateAsyncActions'
can we move it to shared-components?

2021-03-10 14:27 UTC, dimaPortyanka commented on src/auth/Auth.js
> +} from './utils/getMicrosftToken'
why utils?

2021-03-10 14:27 UTC, dimaPortyanka commented on src/auth/Auth.js
> +        init(dispatch)
?

2021-03-10 16:09 UTC, dimaPortyanka commented on package.json
> -    "cross-env": "7.0.3",
should be dev dependency

2021-03-11 06:50 UTC, AnastasiiaManilnikova commented on package.json
> -    "cross-env": "7.0.3",
fixed

2021-03-11 11:31 UTC, dimaPortyanka approved these changes

2021-03-11 11:31 UTC, dimaPortyanka commented on package.json
>      "react-scripts": "4.0.3",
why dev?

2021-03-11 11:33 UTC, merged